### ISSUE TITLE
Transform-Align mesh example

### ISSUE THREAD

**Issue by solub** [wblut/HE_Mesh_Examples#4]
@wblut 

I'm wondering if there is a bug in the transform method. Your Transform-Align mesh example works well with cylinders because orientation doesn't really matter but when using meshes with quad-faces I notice that alignment doesn't fit in the Y direction.

![Annotation 2020-07-07 095727](https://user-images.githubusercontent.com/28729303/86742350-58e00780-c038-11ea-8e69-ed758210f763.png)

Following your example:

```
import peasy.*;

import wblut.core.*;
import wblut.geom.*;
import wblut.hemesh.*;
import wblut.processing.*;

HE_Mesh m1, m2;
PeasyCam cam;

WB_Render3D render;
void setup() {
  size(1000, 1000, P3D);
  perspective(60 * DEG_TO_RAD, width/float(height), 2, 6000);
  smooth(8);
  background(55); 
  render=new WB_Render3D(this);
  cam = new PeasyCam(this, 40);
  create();
}

void create() {

  m1 = new HE_Mesh(new HEC_FromOBJFile("C:/Users/solub/Desktop/m1.obj"));
  m2 =new HE_Mesh(new HEC_FromOBJFile("C:/Users/solub/Desktop/m2.obj"));
  WB_Transform3D T=new WB_Transform3D(m1.getFaceCenter(6), m1.getFaceNormal(6), m2.getFaceCenter(8), m2.getFaceNormal(8).mul(-1));
  m1.transformSelf(T);// or .applySelf(T)
}


void draw() {
  background(50);
  lights();
  stroke(0);
  render.drawFaces(m1);
  render.drawFaces(m2);
}
```

[obj files](https://we.tl/t-vzl3reeP10) if needed.

**Comment by wblut** [comment]
Hi,

the problem is that it is impossible to automatically assign consistent coordinate systems to arbitrary faces. The only fixed direction is the face normal, the z-axis. The tangent and bitangent, the x and y, are entirely dependent on what you want. There's no a priori way to determine the intended orientation.

The best way is to define your own coordinate systems and not rely on the automatically generated coordinate systems of the planar faces.

rgs,

F

**Comment by solub** [comment]
Thank you for the reply, it makes sense now.

I see that _HE_Faces_ have a `getFaceCS()` method but what if I want to assign a _WB_CoordinateSystem_ to it ? For example, could I apply a specific CS to a face of the first mesh and transform that mesh so it aligns with the CS of a face from the second mesh ?

**Comment by wblut** [comment]
Ftm there isno such functionality, but you could create two WB_CoordinateSystems and create a WB_Transform between those.

**Comment by solub** [comment]
That is what I am trying to do but I am having difficulties making the 2 WB_CoordinateSystems match.

I can't seem to output the same configuration as showed on the right of the previous picture:

```
import peasy.*;

import wblut.core.*;
import wblut.geom.*;
import wblut.hemesh.*;
import wblut.processing.*;

HE_Mesh m1, m2;
PeasyCam cam;
WB_Plane plane1, plane2;
WB_CoordinateSystem CS1, CS2;
WB_Vector o1, o2, n1, n2;
int i1, i2;

WB_Render3D render;
void setup() {
  size(1000, 1000, P3D);
  perspective(60 * DEG_TO_RAD, width/float(height), 2, 6000);
  smooth(8);
  background(55); 
  render=new WB_Render3D(this);
  cam = new PeasyCam(this, 40);
  create();
}

void create() {

  m1 = new HE_Mesh(new HEC_FromOBJFile("C:/Users/solub/Desktop/m1.obj"));
  m2 = new HE_Mesh(new HEC_FromOBJFile("C:/Users/solub/Desktop/m2.obj"));
  
  i1 = 6;
  i2 = 8;
  
  plane1 = m1.getFaceWithIndex(i1).getPlane();
  plane2 = m2.getFaceWithIndex(i2).getPlane();
  
  //get origin (face center), direction (face normal) (needed if working with CS ?)
  o1 = m1.getFaceCenter(i1);
  o2 = m2.getFaceCenter(i2);
  n1 = m1.getFaceNormal(i1);
  n2 = m2.getFaceNormal(i2);
  
  CS1 = new WB_CoordinateSystem(plane1);
  CS2 = new WB_CoordinateSystem(plane2);
  
  WB_Transform3D T = new WB_Transform3D().addFromCSToCS(CS1, CS2); //WB_Transform3D(o1, n1, o2, n2.mul(-1))
  m1.transformSelf(T);
}


void draw() {
  background(50);
  lights();
  stroke(0);
  render.drawFaces(m1);
  render.drawFaces(m2);
}
```

![Annotation 2020-07-07 131600](https://user-images.githubusercontent.com/28729303/86772806-03feba00-c055-11ea-9003-ebe5efe739f8.png)

**Comment by wblut** [comment]
Yes, because these CS are the same as the ones defined in the faces, using face center and mormal. The x and/or y axes need to be explicitely defined instead if going through a plane. Note how you're not telling the system what the x and y axes are, only the origin and the z-axis. That's why you have that rotational "freedom". To align them at least one additional axis is needed. I'll add an example.

**Comment by solub** [comment]
I think there is a misunderstanding. 

- I did use the same planes on purpose as a test (that's why I edited my previous post). I will define custom x, y, x axis later.
- However doing so using `addFromCSToCS()` gives a different result from the original sketch. The meshes are not touching each other anymore. It is probably due to an improper use of the method from my part.

**Comment by wblut** [comment]
Hi,

please check this example: https://github.com/wblut/HE_Mesh_Examples/tree/master/2019/examples/geom/transform/ref_WB_Transform_AlignFaces

Please note, I moved the 2019 examples in their own folder.

Cheers

**Comment by op-rt** [comment]
Beautiful and self-explanatory example, thank you so much for your time, it helps a lot.

One last question, is there a reason why you chose `addFromWorldToCS(CS1).addFromCSToWorld(CS2)` over `addFromCSToCS(CS2, CS1)` ? I have noticed they produce different outputs although they "should" (shouldn't they?) be similar.
