### ISSUE TITLE
Straight Skeleton in HE_Mesh

### ISSUE THREAD

**Issue by op-rt** [wblut/HE_Mesh_Examples#5]
Dear @wblut,

Some time ago I posted a [question](https://github.com/wblut/HE_Mesh/issues/10) on HE_Mesh main repository about the `straightskeleton` external package. I was trying to output the Straight Skeleton of a polygon but couldn't manage to find out out how to do so despite all my attempts.

When you have some time, would it be possible to show a simple example ?

Very best

**Comment by op-rt** [comment]
Hi again @wblut ,

I apologize for the inconvenience, I just wanted to know if HE_Mesh could output Straight Skeletons with holes.

And if so, how ? 

Respectfully

**Comment by wblut** [comment]
Hi,

no. The library I rely on doesn't support polygons with holes. One workaround would be to turn the polygon with holes into a "simple polygon" by connecting the holes to the outline. However, the straight skeleton will not be a connected loop.

f

**Comment by op-rt** [comment]
As always, many thanks for the swift reply !
